name = "nomapet"
pages_build_output_dir = "."

compatibility_date = "2026-08-14"

[[d1_databases]]
binding = "DB"
database_name = "nomapet-db"
database_id = "62c49f12-1234-5678-9012-abcdef123456"