name = "nomapet"
pages_build_output_dir = "."

compatibility_date = "2026-08-14"

[[d1_databases]]
binding = "DB"
database_name = "nomapet-db"
database_id = "dd15a1c4-0a74-4875-b6a7-04a136fa539a"